---

- name: IOS Privileges
  hosts: pynet-rtr1
  vars:
    creds:
      host: "{{ ansible_host }}" #from ansible-hosts.txt
      username: test1
      password: "{{ password }}"
      authorize: True
      auth_pass: "{{ password }}"
  tasks:
    - ios_facts:
        provider: "{{ creds }}"
    - ios_command:
        provider: "{{ creds }}" 
        commands: show run 