---

- name: IOS SSH
  hosts: pynet-rtr1
  vars:
    creds:
      host: "{{ ansible_host }}" #from ansible-hosts.txt
      username: testuser
      ssh_keyfile: ~/.ssh/test_rsa
  tasks:
    - ios_facts:
        provider: "{{ creds }}"
    - ios_command:
        provider: "{{ creds }}" 
        commands: show ip int brief       