---

- name: IOS Config
  hosts: pynet-rtr1
  tasks:
    - ios_config:
        provider: "{{ creds_ssh }}"
        lines:
          - "ip domain name {{ default_domain }}"
          - "ip name-server {{ name_server1 }}"
          - "ip name-server {{ name_server2 }}"
          - "ntp server {{ ntp1 }}"
          - "ntp server {{ ntp2 }}"  
- name: EOS Config
  hosts: pynet-sw5
  tasks:
    - eos_config:
        provider: "{{ creds_eapi }}"
        lines:
          - "ip domain name {{ default_domain }}"
          - "ip name-server vrf {{ name_server1 }}"
          - "ip name-server vrf {{ name_server2 }}"
          - "ntp server {{ ntp1 }}"
          - "ntp server {{ ntp2 }}"
- name: NXOS Config
  hosts: nxos1
  tasks:
    - nxos_config:
        provider: "{{ creds_nxapi }}"
        lines:
          - "ip domain name {{ default_domain }}"
          - "ip name-server {{ name_server1 }} {{ name_server2 }}"
          - "ntp server {{ ntp1 }}"
          - "ntp server {{ ntp2 }}"                        