---

# Construct a playbook using the ‘eos_command’ module and eAPI. 
# Run 'show arp' against the 'pynet-sw7' switch. 
# From this output obtain the MAC address corresponding to 10.220.88.1 and assign it to a variable named gateway_mac (use the set_fact module here). 
# Print the 'gateway_mac' to the screen. Hint: create an intermediate variable that is the mac_table and then use with_items to loop over this mac_table.

- name: Class2 Ex4
  hosts: pynet-sw7
  vars:
    eapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      use_ssl: True
      validate_certs: no
  tasks:
    - name: EOS Facts
      eos_facts:
        provider: "{{ eapi }}"
    - name: ARP
      eos_command:
        provider: "{{ eapi }}"
        commands: show arp
      register: show_arp
   - name: Set Table Var
     set_fact:
       gateway_mac: "{{ item.hwAddress }}" 
     with_items: "{{ mac_table }}"
     when: item.address == '10.220.88.1' 
   - name: Print Gateway
     debug:
       var: gateway_mac             