---

# Where X.X is some random network in the 10-net
# Where :XXXX: is some random IPv6 hex digits
# nxos2:    IPv4: 10.X.X.2/24
#           IPv6: 2001::db8:XXXX:200c:2/64

ip_addresses:
   ip_four: 10.10.10.2
   ip_six: 2001::db8:ac10:200c:2